# Generated by Django 4.2.2 on 2023-07-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='id',
        ),
        migrations.AddField(
            model_name='juego',
            name='codigo',
            field=models.CharField(default=0, max_length=6, primary_key=True, serialize=False, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
